const LIMITER_RANGE_FOR_LIMIT_ORDERS = 2; // %
const REMOVE_INACTIVE_LIMIT_ORDERS_AFTER = 7200; // seconds

module.exports = {
  LIMITER_RANGE_FOR_LIMIT_ORDERS,
  REMOVE_INACTIVE_LIMIT_ORDERS_AFTER,
};
