const DEFAULT_INDENT_IN_PERCENTS = 3; // %
const TYPE_CANDLES_FOR_FIND_LEVELS = ['1h', '4h', '1d'];

const MIN_AMOUNT_CANDLES_FOR_CALCULATE_LEVELS = 20;

module.exports = {
  DEFAULT_INDENT_IN_PERCENTS,
  TYPE_CANDLES_FOR_FIND_LEVELS,
  MIN_AMOUNT_CANDLES_FOR_CALCULATE_LEVELS,
};
