const DISTANCE_FROM_LEFT_SIDE = 100;
const DISTANCE_FROM_RIGHT_SIDE = 100;

/*
const DEFAULT_INDENT_IN_PERCENTS = 3; // %
const TYPE_CANDLES_FOR_FIND_LEVELS = ['1h', '4h', '1d'];
const MIN_AMOUNT_CANDLES_FOR_CALCULATE_LEVELS = 20;
*/

module.exports = {
  DISTANCE_FROM_LEFT_SIDE,
  DISTANCE_FROM_RIGHT_SIDE,
};
