const FACTOR_FOR_VOLUME_CHANGE = 3;
const NUMBER_CANDLES_FOR_CALCULATE_AVERAGE_PERCENT_FOR_5M = 36; // 3 hours (5m)
const NUMBER_CANDLES_FOR_CALCULATE_AVERAGE_PERCENT_FOR_1H = 12; // 12 hours (1h)

const DOES_CONSIDER_BTC_MICRO_TREND = false;
const DOES_CONSIDER_FUTURES_MICRO_TREND = false;

const STOPLOSS_PERCENT = 0.5; // %

module.exports = {
  FACTOR_FOR_VOLUME_CHANGE,

  NUMBER_CANDLES_FOR_CALCULATE_AVERAGE_PERCENT_FOR_5M,
  NUMBER_CANDLES_FOR_CALCULATE_AVERAGE_PERCENT_FOR_1H,

  DOES_CONSIDER_BTC_MICRO_TREND,
  DOES_CONSIDER_FUTURES_MICRO_TREND,

  STOPLOSS_PERCENT,
};
